
name: Static Analysis with SARIF Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  static_analysis:
    runs-on: [self-hosted, linux]  # Specify your self-hosted runner's labels

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Upload the SARIF file as an artifact
    - name: Upload SARIF Report
      uses: actions/upload-artifact@v3
      with:
        name: SARIFREPORT
        path: result.sarif
